Commandes:
  admin:
    name: Equipe Dev
    email: dev@polytech.edu.sn

spring:
  application:
    name: Commandes

  datasource:
    username: ${DB_USER:root}
    password: ${DB_PWD:root123}
    url: ${DB_URL:jdbc:mysql://localhost:3306/commandes_dev}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 8080
