Commandes:
  admin:
    name: Equipe Dev
    email: dev@polytech.edu.sn

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
 
    url: ${DB_URL:jdbc:mysql://localhost:3306/commandes_dev}
   
